### ISSUE TITLE
參數化

### ISSUE THREAD

**Issue by tigercosmos** [behappycc/fb-lottery#3]
直接設計成輸入參數來跑會更方便吧

**Comment by behappycc** [comment]
Hi tigercosmos, 你的意思是設計GUI介面讓使用者直接輸入參數嗎?

**Comment by tigercosmos** [comment]
現在要直接去改動 `py` 檔，可以把它設計成輸入參數 `python fb_lottery.py --url={url} --token={token}`
圖形化我覺得也是個好點子 XD
